### ISSUE TITLE
.NET Core client

### ISSUE THREAD

**Issue by rohitjha** [1Forge/dotnet-forex-quotes#2]
I recently came across your API but I did not find a .NET Core client for it. So here's a simple one which I wrote: https://github.com/rohitjha/dotnet-core-forex-quotes and I thought of informing you about it. This client's code and behavior should be very similar to the .NET Framework client.

**Comment by brutus-gr** [comment]
@rohitjha Thanks for this!  I have sent you an e-mail about possibly working together.
